"""Allowed settings and callable hooks for this project."""

STAGE_KEYS = {'cache': ['DATA_DIR',
           'LOG_LEVEL',
           'MARKET_TICKER',
           'FEATURE_WARMUP_YEARS',
           'TARGET_LOOKAHEAD_DAYS',
           'DEFAULT_TOKENS',
           'STOCK_TYPE',
           'TOKENS',
           'DOWNLOAD_START',
           'DOWNLOAD_END',
           'TRAIN_END',
           'BACKTEST_START',
           'BACKTEST_END'],
 'horizons': ['RESEARCH_START',
              'HORIZON_VALIDATION_START',
              'DATA_DIR',
              'LOG_LEVEL',
              'RESEARCH_END',
              'HORIZON_VALIDATION_FRACTION',
              'STOCK_TYPE',
              'HORIZON_SCORE_VALUES',
              'REBALANCE_MULTIPLIER',
              'HORIZON_TEST_TYPE_CONFIGURATIONS',
              'HORIZON_TEST_MAX_WEIGHTS',
              'HORIZON_TEST_CONCENTRATION_PENALTIES',
              'HORIZON_FREEZE_BQ_RANGE',
              'NEAR_BEST_BQ_TOLERANCE',
              'CONFIGURATION_CORRELATION_THRESHOLD',
              'ANALYSIS_MODE',
              'HORIZON_SETTING_MODE',
              'RANDOM_SCREENS',
              'EXTRA_RANDOM_SCREENS',
              'MAX_EXHAUSTIVE_CONFIGURATIONS'],
 'precise': ['FE_NEIGHBOURHOOD_SD',
             'DATA_DIR',
             'LOG_LEVEL',
             'PORTFOLIO_GROUP_CONFIGURATIONS',
             'FE_TRADING_FEE',
             'FE_RF_ANNUAL',
             'FE_DSR_SAMPLE_SIZE',
             'FE_DSR_TRIALS',
             'FE_SEED',
             'FE_DAYS',
             'FE_UNSEEN_GATE',
             'OUTPUT_DIR'],
 'simulations': ['DATA_DIR',
                 'LOG_LEVEL',
                 'REBALANCE_MULTIPLIERS',
                 'CONCENTRATION_PENALTIES',
                 'MAX_WEIGHTS',
                 'PORTFOLIO_GROUP_CONFIGURATIONS',
                 'PORTFOLIO_TYPE_REJECTION_THRESHOLDS',
                 'PRIMARY_REJECTION_TYPES',
                 'SECONDARY_REJECTION_TYPES',
                 'TERTIARY_REJECTION_TYPES',
                 'portfolio_group_robustness_threshold',
                 'number_of_iterations',
                 'settings_robustness_threshold',
                 'unseen_stock_robustness_threshold',
                 'return_correlation_threshold',
                 'performance_percentage_threshold',
                 'stock_overlap_threshold']}

STAGE_CALLBACKS = {'cache': ['run_step',
           'add_all_individual_features',
           'create_market_breadth_and_dispersion',
           'add_all_time_series_targets',
           'finish_dataframe',
           'dataframe_memory_mb',
           'horizon_key',
           'purged_training_end',
           'apply_horizon_signal_refresh',
           'get_target_orientation',
           'prediction_to_signal'],
 'horizons': ['RESEARCH_START',
              'HORIZON_VALIDATION_START',
              'quote_sql_identifier',
              'dataframe_memory_mb',
              'target_sql_columns',
              'load_target_period',
              'horizon_key',
              'reference_horizon_score',
              'get_horizon_score',
              'apply_horizon_signal_refresh',
              'get_target_orientation',
              'prediction_to_signal',
              'normalize_horizon_scores_by_type_group',
              'apply_type_configuration',
              'backtest_quality',
              'random_screen',
              'normalize_horizon_configuration',
              'configuration_vector'],
 'precise': ['FE_NEIGHBOURHOOD_SD'],
 'simulations': ['extract_type_score_columns',
                 'result_metrics',
                 'run_simulations',
                 'save_final_evaluation_values',
                 'stop_if_no_simulations',
                 'type_score_rejection',
                 'configuration_distance',
                 'get_two_closest_configurations',
                 'percentage_from_pair_median',
                 'average_stock_overlap']}
