from equity_selector.config import data_root as project_data_root
"""Edit SETTINGS here, then run this script. CLI path/log options override these values.
None retains optional defaults; required cache dates must be set here. Packages never prompt.
"""

from equity_selector.cli import run_stage

LEARNING_RATES = [0.05]

SETTINGS = {
    # legacy preserves the original explicit lists; grid uses the *_PARAMS grids below.
    "MODEL_CATALOGUE_MODE": "legacy", # 'legacy' or 'grid'
    "DATA_DIR": str(project_data_root()),
    "LOG_LEVEL": "INFO",
    "STOCK_TYPE": "High Liquidity 30",
    "MAX_CONTINUOUS_RANK_IC_STD": 0.1,
    "MAX_BINARY_ROC_AUC_STD": 0.07,
    "MAX_MULTICLASS_MACRO_F1_STD": 0.1,
    "RIDGE_ALPHAS": [1e-05, 3e-05, 0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000, 3000, 10000],
    "SPARSE_ALPHAS": [1e-08, 1e-07, 1e-06, 1e-05, 0.0001, 0.001, 0.01, 0.1, 0.3, 1, 3, 10],  
    "Targets": None,
    "C_VALUES": [0.1],
    "L1_RATIOS": [0.5],
    "LEARNING_RATES": LEARNING_RATES,
    "CLASS_WEIGHTS": [None, "balanced"],
    "HIST_GRADIENT_PARAMS": {
        "learning_rate": LEARNING_RATES,
        "max_iter": [200],
        "max_leaf_nodes": [31],
        "max_depth": [5],
        "min_samples_leaf": [20],
        "l2_regularization": [0.1],
    },
    "GRADIENT_BOOSTING_PARAMS": {
        "learning_rate": LEARNING_RATES,
        "n_estimators": [200],
        "max_depth": [3],
        "min_samples_leaf": [20],
        "subsample": [0.8],
        "max_features": ["sqrt"],
    },
    "RANDOM_FOREST_PARAMS": {
            "n_estimators": [200],
            "max_depth": [10],
            "min_samples_leaf": [5],
            "min_samples_split": [5],
            "max_features": ["sqrt"],
            "bootstrap": [True],
    },
    "XGBOOST_PARAMS": {
            "n_estimators": [200],
            "learning_rate": LEARNING_RATES,
            "max_depth": [3],
            "min_child_weight": [1],
            "subsample": [0.8],
            "colsample_bytree": [0.75],
            "gamma": [0],
            "reg_alpha": [0],
            "reg_lambda": [1],
    },
    "LIGHTGBM_PARAMS": {
            "n_estimators": [200, 300],
            "learning_rate": LEARNING_RATES,
            "num_leaves": [7, 15],
            "max_depth": [-1],
            "min_child_samples": [10, 20],
            "subsample": [0.8],
            "colsample_bytree": [0.75],
            "reg_alpha": [0, 0.1],
            "reg_lambda": [1],
    },   
    "MLP_PARAMS": {
            "hidden_layer_sizes": [(64,)],
            "activation": ["relu"],
            "alpha": [0.0001],
            "learning_rate_init": [0.001],
            "batch_size": [128],
    },    
    "KNN_PARAMS": {
            "n_neighbors": [3, 5, 10, 20, 40, 80, 150, 250],
            "weights": ["uniform", "distance"],
            "p": [1, 2],
    },

    "LEGACY_CONTINUOUS_MODELS": [
        {"name": "Ridge", "params": {"alpha": 0.001}},
        {"name": "Ridge", "params": {"alpha": 1000}},
        {"name": "Ridge", "params": {"alpha": 10000}},
        {"name": "Lasso", "params": {"alpha": 0.0001}},
        {"name": "Lasso", "params": {"alpha": 0.001}},
        {"name": "Lasso", "params": {"alpha": 0.01}},
        {"name": "Elastic Net", "params": {"alpha": 0.0001, "l1_ratio": 0.5}},
        {"name": "Elastic Net", "params": {"alpha": 0.001, "l1_ratio": 0.5}},
        {"name": "Elastic Net", "params": {"alpha": 0.01, "l1_ratio": 0.5}},
        {"name": "Huber", "params": {"epsilon": 1.35, "alpha": 0.0001}},
        {"name": "Huber", "params": {"epsilon": 1.75, "alpha": 0.001}},
        {"name": "Hist Gradient Boosting", "params": {"learning_rate": 0.05, "max_iter": 200, "max_leaf_nodes": 7, "max_depth": None, "min_samples_leaf": 50, "l2_regularization": 1.0}},
        {"name": "Hist Gradient Boosting", "params": {"learning_rate": 0.05, "max_iter": 200, "max_leaf_nodes": 15, "max_depth": None, "min_samples_leaf": 50, "l2_regularization": 1.0}},
        {"name": "Random Forest", "params": {"n_estimators": 200, "max_depth": 8, "min_samples_leaf": 20, "min_samples_split": 5, "max_features": "sqrt", "bootstrap": True}},
        {"name": "Random Forest", "params": {"n_estimators": 200, "max_depth": 12, "min_samples_leaf": 50, "min_samples_split": 5, "max_features": "sqrt", "bootstrap": True}},
        {"name": "XGBoost", "params": {"n_estimators": 200, "learning_rate": 0.05, "max_depth": 3, "min_child_weight": 10, "subsample": 0.8, "colsample_bytree": 0.8, "gamma": 0, "reg_alpha": 0, "reg_lambda": 10}},
        {"name": "XGBoost", "params": {"n_estimators": 200, "learning_rate": 0.05, "max_depth": 3, "min_child_weight": 10, "subsample": 0.8, "colsample_bytree": 0.8, "gamma": 0, "reg_alpha": 0, "reg_lambda": 1}},
        {"name": "LightGBM", "params": {"n_estimators": 200, "learning_rate": 0.05, "num_leaves": 15, "max_depth": -1, "min_child_samples": 50, "subsample": 1.0, "colsample_bytree": 0.8, "reg_alpha": 0, "reg_lambda": 10}},
        {"name": "LightGBM", "params": {"n_estimators": 200, "learning_rate": 0.05, "num_leaves": 15, "max_depth": -1, "min_child_samples": 50, "subsample": 1.0, "colsample_bytree": 0.8, "reg_alpha": 0, "reg_lambda": 1}},
        {"name": "Gradient Boosting", "params": {"learning_rate": 0.05, "n_estimators": 150, "max_depth": 2, "min_samples_leaf": 50, "subsample": 0.8, "max_features": "sqrt"}},
    ],
    "LEGACY_BINARY_MODELS": [
        {"name": "L2 Logistic Regression", "params": {"C": 0.01, "class_weight": None}},
        {"name": "L2 Logistic Regression", "params": {"C": 0.01, "class_weight": "balanced"}},
        {"name": "L2 Logistic Regression", "params": {"C": 0.1, "class_weight": None}},
        {"name": "L2 Logistic Regression", "params": {"C": 0.1, "class_weight": "balanced"}},
        {"name": "L2 Logistic Regression", "params": {"C": 1.0, "class_weight": None}},
        {"name": "L2 Logistic Regression", "params": {"C": 1.0, "class_weight": "balanced"}},
        {"name": "L1 Logistic Regression", "params": {"C": 0.1, "class_weight": None}},
        {"name": "L1 Logistic Regression", "params": {"C": 0.1, "class_weight": "balanced"}},
        {"name": "L1 Logistic Regression", "params": {"C": 1.0, "class_weight": None}},
        {"name": "L1 Logistic Regression", "params": {"C": 1.0, "class_weight": "balanced"}},
        {"name": "Elastic Net Logistic Regression", "params": {"C": 0.1, "l1_ratio": 0.5, "class_weight": None}},
        {"name": "Elastic Net Logistic Regression", "params": {"C": 0.1, "l1_ratio": 0.5, "class_weight": "balanced"}},
        {"name": "Hist Gradient Boosting", "params": {"learning_rate": 0.05, "max_iter": 200, "max_leaf_nodes": 7, "max_depth": None, "min_samples_leaf": 50, "l2_regularization": 1.0, "class_weight": None}},
        {"name": "Hist Gradient Boosting", "params": {"learning_rate": 0.05, "max_iter": 200, "max_leaf_nodes": 7, "max_depth": None, "min_samples_leaf": 50, "l2_regularization": 1.0, "class_weight": "balanced"}},
        {"name": "Hist Gradient Boosting", "params": {"learning_rate": 0.05, "max_iter": 200, "max_leaf_nodes": 15, "max_depth": None, "min_samples_leaf": 50, "l2_regularization": 1.0, "class_weight": None}},
        {"name": "Hist Gradient Boosting", "params": {"learning_rate": 0.05, "max_iter": 200, "max_leaf_nodes": 15, "max_depth": None, "min_samples_leaf": 50, "l2_regularization": 1.0, "class_weight": "balanced"}},
        {"name": "Random Forest", "params": {"n_estimators": 200, "max_depth": 8, "min_samples_leaf": 20, "min_samples_split": 5, "max_features": "sqrt", "bootstrap": True, "class_weight": None}},
        {"name": "Random Forest", "params": {"n_estimators": 200, "max_depth": 8, "min_samples_leaf": 20, "min_samples_split": 5, "max_features": "sqrt", "bootstrap": True, "class_weight": "balanced"}},
        {"name": "Random Forest", "params": {"n_estimators": 200, "max_depth": 12, "min_samples_leaf": 50, "min_samples_split": 5, "max_features": "sqrt", "bootstrap": True, "class_weight": None}},
        {"name": "Random Forest", "params": {"n_estimators": 200, "max_depth": 12, "min_samples_leaf": 50, "min_samples_split": 5, "max_features": "sqrt", "bootstrap": True, "class_weight": "balanced"}},
        {"name": "XGBoost", "params": {"n_estimators": 200, "learning_rate": 0.05, "max_depth": 3, "min_child_weight": 10, "subsample": 0.8, "colsample_bytree": 0.8, "gamma": 0, "reg_alpha": 0, "reg_lambda": 10, "class_weight": None}},
        {"name": "XGBoost", "params": {"n_estimators": 200, "learning_rate": 0.05, "max_depth": 3, "min_child_weight": 10, "subsample": 0.8, "colsample_bytree": 0.8, "gamma": 0, "reg_alpha": 0, "reg_lambda": 10, "class_weight": "balanced"}},
        {"name": "LightGBM", "params": {"n_estimators": 200, "learning_rate": 0.05, "num_leaves": 15, "max_depth": -1, "min_child_samples": 50, "subsample": 1.0, "colsample_bytree": 0.8, "reg_alpha": 0, "reg_lambda": 10, "class_weight": None}},
        {"name": "LightGBM", "params": {"n_estimators": 200, "learning_rate": 0.05, "num_leaves": 15, "max_depth": -1, "min_child_samples": 50, "subsample": 1.0, "colsample_bytree": 0.8, "reg_alpha": 0, "reg_lambda": 10, "class_weight": "balanced"}},
    ],
    "LEGACY_MULTICLASS_MODELS": [
        {"name": "L2 Multinomial Logistic Regression", "params": {"C": 0.01, "class_weight": None}},
        {"name": "L2 Multinomial Logistic Regression", "params": {"C": 0.01, "class_weight": "balanced"}},
        {"name": "L2 Multinomial Logistic Regression", "params": {"C": 0.1, "class_weight": None}},
        {"name": "L2 Multinomial Logistic Regression", "params": {"C": 0.1, "class_weight": "balanced"}},
        {"name": "L1 Multinomial Logistic Regression", "params": {"C": 0.1, "class_weight": None}},
        {"name": "L1 Multinomial Logistic Regression", "params": {"C": 0.1, "class_weight": "balanced"}},
        {"name": "Elastic Net Multinomial Logistic Regression", "params": {"C": 0.1, "l1_ratio": 0.5, "class_weight": None}},
        {"name": "Elastic Net Multinomial Logistic Regression", "params": {"C": 0.1, "l1_ratio": 0.5, "class_weight": "balanced"}},
        {"name": "Hist Gradient Boosting", "params": {"learning_rate": 0.05, "max_iter": 200, "max_leaf_nodes": 7, "max_depth": None, "min_samples_leaf": 50, "l2_regularization": 1.0, "class_weight": None}},
        {"name": "Hist Gradient Boosting", "params": {"learning_rate": 0.05, "max_iter": 200, "max_leaf_nodes": 7, "max_depth": None, "min_samples_leaf": 50, "l2_regularization": 1.0, "class_weight": "balanced"}},
        {"name": "Hist Gradient Boosting", "params": {"learning_rate": 0.05, "max_iter": 200, "max_leaf_nodes": 15, "max_depth": None, "min_samples_leaf": 50, "l2_regularization": 1.0, "class_weight": None}},
        {"name": "Hist Gradient Boosting", "params": {"learning_rate": 0.05, "max_iter": 200, "max_leaf_nodes": 15, "max_depth": None, "min_samples_leaf": 50, "l2_regularization": 1.0, "class_weight": "balanced"}},
        {"name": "Random Forest", "params": {"n_estimators": 200, "max_depth": 8, "min_samples_leaf": 20, "min_samples_split": 5, "max_features": "sqrt", "bootstrap": True, "class_weight": None}},
        {"name": "Random Forest", "params": {"n_estimators": 200,"max_depth": 8, "min_samples_leaf": 20, "min_samples_split": 5, "max_features": "sqrt", "bootstrap": True, "class_weight": "balanced"}},
        {"name": "Random Forest", "params": {"n_estimators": 200, "max_depth": 12, "min_samples_leaf": 50, "min_samples_split": 5, "max_features": "sqrt", "bootstrap": True, "class_weight": None}},
        {"name": "Random Forest", "params": {"n_estimators": 200, "max_depth": 12, "min_samples_leaf": 50, "min_samples_split": 5, "max_features": "sqrt", "bootstrap": True, "class_weight": "balanced"}},
        {"name": "XGBoost", "params": {"n_estimators": 200, "learning_rate": 0.05, "max_depth": 3, "min_child_weight": 10, "subsample": 0.8, "colsample_bytree": 0.8, "gamma": 0, "reg_alpha": 0, "reg_lambda": 10, "class_weight": None}},
        {"name": "XGBoost", "params": {"n_estimators": 200, "learning_rate": 0.05, "max_depth": 3, "min_child_weight": 10, "subsample": 0.8, "colsample_bytree": 0.8, "gamma": 0, "reg_alpha": 0, "reg_lambda": 10, "class_weight": "balanced"}},
        {"name": "LightGBM", "params": {"n_estimators": 200, "learning_rate": 0.05, "num_leaves": 15, "max_depth": -1, "min_child_samples": 50, "subsample": 1.0, "colsample_bytree": 0.8, "reg_alpha": 0, "reg_lambda": 10, "class_weight": None}},
        {"name": "LightGBM", "params": {"n_estimators": 200, "learning_rate": 0.05, "num_leaves": 15, "max_depth": -1, "min_child_samples": 50, "subsample": 1.0, "colsample_bytree": 0.8, "reg_alpha": 0, "reg_lambda": 10, "class_weight": "balanced"}},
        {"name": "LDA LSQR/Eigen", "params": {"solver": "lsqr", "shrinkage": 0.1}},
        {"name": "LDA LSQR/Eigen", "params": {"solver": "lsqr", "shrinkage": 0.5}},
        {"name": "QDA", "params": {"reg_param": 0.1}},
        {"name": "Ordinal Regression", "params": {"alpha": 1.0}},
    ],
    "TEST_RECOMMENDATIONS": False,
    "N_RECOMMENDATIONS": 5,
    "N_MODELS": 3,
    "PRUNING_STAGES": {
        3: (0.95, 20000),
        5: (0.90, 5000),
        7: (0.80, 1000),
        9: (0.65, 300),
        11: (0.50, 70),
        14: (0.50, 15),
    },
    "VALIDATION_WINDOW": 63,
    "MIN_VALIDATION_FOLDS": 15,
    "RESEARCH_START": "2000-01-01",
    "RESEARCH_END": "2015-12-31",
    "MODEL_TRAIN_END": "2006-12-31",
    "MODEL_VALIDATION_END": "2012-12-31",
}

# Optional named helper replacements with the same signature; normally leave empty.
CALLBACKS = {}

if __name__ == "__main__":
    run_stage("training", settings=SETTINGS, callbacks=CALLBACKS)
